// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whckoleflooauwxsrzjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoY2tvbGVmbG9vYXV3eHNyempnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMjk0NzIsImV4cCI6MjA3MjgwNTQ3Mn0.Rz-tq-inB_IFO1zsfJlHAYeYG6ANVHDSCgR4r401PTI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});